# Generated by Django 3.2.9 on 2021-11-28 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
